Create two tensors (named A, B) of shape (5, 5) that are filled with random numbers, and complete
 the following operations:
 • Create a zero tensor (named C) of the same shape and dtype as the tensors.
 • Perform and print the result of the following operations of A and B: addition, subtraction,
 element-wise multiplication, and matrix multiplication.

In [1]:
import torch

# 创建两个5x5的随机张量A和B
A = torch.rand(5, 5)
B = torch.rand(5, 5)

# 创建一个与A、B同形状和类型的零张量C
C = torch.zeros_like(A)

# 加法
add_result = A + B
print("A + B =\n", add_result)

# 减法
sub_result = A - B
print("A - B =\n", sub_result)

# 元素乘法
mul_result = A * B
print("A * B (element-wise) =\n", mul_result)

# 矩阵乘法
matmul_result = torch.matmul(A, B)
print("A @ B (matrix multiplication) =\n", matmul_result)

A + B =
 tensor([[1.7790, 0.5062, 1.3955, 1.6710, 0.9733],
        [1.7298, 0.3935, 0.7908, 0.7819, 0.6220],
        [1.0913, 0.4304, 0.6222, 0.8630, 1.5228],
        [1.5770, 0.8360, 1.7286, 1.2311, 0.9465],
        [0.4346, 0.8598, 0.5384, 1.2175, 1.1269]])
A - B =
 tensor([[ 0.0775,  0.0571,  0.2896, -0.1660,  0.7076],
        [-0.2579,  0.2330,  0.3162, -0.1671,  0.0483],
        [ 0.6622, -0.0254, -0.0799,  0.1836, -0.2658],
        [-0.2583, -0.0314, -0.1148,  0.7662,  0.0972],
        [ 0.1412,  0.8418,  0.2039,  0.6644, -0.8090]])
A * B (element-wise) =
 tensor([[0.7897, 0.0633, 0.4659, 0.6912, 0.1116],
        [0.7314, 0.0251, 0.1313, 0.1459, 0.0961],
        [0.1881, 0.0461, 0.0952, 0.1778, 0.5620],
        [0.6051, 0.1745, 0.7437, 0.2321, 0.2216],
        [0.0422, 0.0076, 0.0621, 0.2602, 0.1538]])
A @ B (matrix multiplication) =
 tensor([[2.0642, 0.7570, 1.7100, 1.6798, 2.0906],
        [1.3874, 0.4529, 1.0150, 1.1768, 1.1375],
        [1.5777, 0.5075, 1.2154, 1.2890, 1.2476

 Create a tensor of shape (6, 4) filled with random numbers, and complete the following operations:
 • Reshape it to be of shape (24,), and print the result.
 • Extract and print a (4, 2) sub-tensor from the middle of the original tensor.

In [2]:
# 创建一个6x4的随机张量
tensor = torch.rand(6, 4)
print("Original tensor (6, 4):\n", tensor)

# 重塑为(24,)
reshaped = tensor.reshape(24)
print("Reshaped tensor (24,):\n", reshaped)

# 从中间提取一个(4, 2)的子张量
# 取第1~4行（索引1:5），第1~2列（索引1:3）
sub_tensor = tensor[1:5, 1:3]
print("Middle sub-tensor (4, 2):\n", sub_tensor)

Original tensor (6, 4):
 tensor([[0.9501, 0.2430, 0.1173, 0.1766],
        [0.6241, 0.6702, 0.7641, 0.3322],
        [0.3313, 0.7489, 0.0295, 0.1985],
        [0.2016, 0.2495, 0.8594, 0.0105],
        [0.0809, 0.9695, 0.1555, 0.4288],
        [0.5936, 0.4809, 0.8798, 0.4334]])
Reshaped tensor (24,):
 tensor([0.9501, 0.2430, 0.1173, 0.1766, 0.6241, 0.6702, 0.7641, 0.3322, 0.3313,
        0.7489, 0.0295, 0.1985, 0.2016, 0.2495, 0.8594, 0.0105, 0.0809, 0.9695,
        0.1555, 0.4288, 0.5936, 0.4809, 0.8798, 0.4334])
Middle sub-tensor (4, 2):
 tensor([[0.6702, 0.7641],
        [0.7489, 0.0295],
        [0.2495, 0.8594],
        [0.9695, 0.1555]])


Autograd
Create a tensor of size (3, 3) with requires_grad=True. Perform following operations:
 Multiple with the tensor [[1, 0, 2], [1, 1, 0], [0, 3, 1]] and sum up the elements of the resulting tensor.
 Then, calculate and print the gradient of the operations with respect to the original tensor.

In [4]:
# 创建一个3x3的张量，requires_grad=True
X = torch.rand(3, 3, requires_grad=True)
# 定义给定的常量张量
W = torch.tensor([[1., 0., 2.],
                  [1., 1., 0.],
                  [0., 3., 1.]])
# 乘法并求和
Z = torch.mm(X, W)
output = Z.sum()
# 反向传播，计算梯度
output.backward()
# 打印梯度
print("Gradient of X:\n", X.grad)


Gradient of X:
 tensor([[3., 2., 4.],
        [3., 2., 4.],
        [3., 2., 4.]])
